services:
  database:
    container_name: "em-postgres-db"
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      DATABASE_URL: jdbc:postgresql://postgres-db:5432/postgres
    volumes:
      - ./event-manager-db:/var/lib/event-manager-db
    ports:
      - "5432:5432"

  event-manager:
    build: .
    container_name: "event-manager"
    restart: always
    depends_on:
      - database
      - kafka
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: 12345
      DDL_AUTO: create-drop
    ports:
      - "8081:8081"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"